hyperboria/peers

EU/se/stockholm/leeloo.kyriasis.com.k
Though connectTo overflow bug should be fixed any day now as well, thankfully.
=> EU/se/stockholm/leeloo: Use shorter version of snippet

.travis.yml, EU/nl/amsterdam/mrowr.me.k, EU/uk/london/ansuz.science.k, README.md, tests.py
This should fix #7 and #18, although further testing should also be added eventually
=> Add basic tests

AS/sg/singapore/weuxel.sing.k, EU/de/bavaria/hype.jazzanet.com.k, EU/fr/nord-pas-de-calais/hub.icfreedom.net.k, EU/fr/strasbourg/magik6k.net.k, EU/gr/rethymno/kaotisk.rethymno-meshnet.k, EU/nl/amsterdam/mrowr.me.k, EU/nl/amsterdam/weuxel.ams.k, EU/ru/moscow/h.bunjlabs.com.k, EU/se/stockholm/leeloo.kyriasis.com.k, EU/uk/london/ansuz.science.k, NA/ca/beauharnois/derp.fusion.k, NA/us/california/igel-california.usa.k, NA/us/newyork/jacobhenner.usa.k, NA/us/newyork/weuxel.usa.k, NA/us/northcarolina/igel-northcarolina.usa.k, NA/us/pennsylvania/nat.usa.k, README.md, tests.py
Along the lines of #40, but with actual JSON that can be parsed without modification by any JSON parser, a `test.py` modification to check that future submissions comply with formatting guidelines, and a `test.py` flag (`--clean`) to auto-format your ugly submissions before you submit them
=> Pretty JSON

NA/ca/quebec/ca.hub.icfreedom.net.k
=> quebec node

EU/fr/nord-pas-de-calais/play.fallofanempire.com.k
=> fallofanempire node

EU/nl/amsterdam/florianb.ams.k
=> New Node in AMS

AS/hk/hk.hub.icfreedom.net.k, AS/sg/singapore/sg.hub.icfreedom.net.k, EU/fr/nord-pas-de-calais/hub.icfreedom.net.k, EU/fr/nord-pas-de-calais/play.fallofanempire.com.k, EU/gr/rethymno/kaotisk.rethymno-meshnet.k, EU/md/chisinau/eu-east.hub.icfreedom.net.k, NA/ca/quebec/ca.hub.icfreedom.net.k, NA/us/oregon/h.us-west.hub.icfreedom.net.k
I resolved the dns records for all credentials that didn't use raw IPs and replaced the domains with the results.
=> remove nodes which rely on dns

na/us/texas/dallas.trnsz.k
=> dallas public node

as/sg/tanjong-pagar-centre.k
Hallo!
Here's a Digital Ocean droplet in their Singapore data center that folks can connect to :)
=> Public peer in Singapore data center.

na/us/california/san-francisco/salesforce-tower.k
Hello!
I have a droplet in a SF data center that folks can connect to if they're looking for a connection :)
=> Public peer around SF, CA, USA ("salesforce-tower")

as/in/karnataka/bangalore/mantri-pinnacle.k
Hello again!
I have a DigitalOcean droplet hanging out in their Bangalore data center if anyone wants to connect to it :)
=> Public peer around Bangalore, India

na/us/california/san-francisco/kylerchin-website.k
I have peered with other digitalocean servers to make fast connectivity on Hyperboria and speed up traffic for peers closer to data centers.
=>  kylerchin-website.k on my DigitalOcean server!

eu/ua/kiev/kiev/ic.hellomouse.cf.k, na/us/northcarolina/charlotte/ic2.hellomouse.cf.k
Add ic.hellomouse.cf and ic2.hellomouse.cf
=> Add my peers

na/ca/ontario/linux1.tor1.watters.ws.k
This node is a droplet located in Toronto, CA.
=> Add linux1.tor1.watters.ws node

eu/nl/amsterdam/mrowr.me.k, eu/nl/amsterdam/weuxel.ams.k, na/us/chicago/cornfeedhobo.chicago.usa.k, tests.py
This is important to prevent peers from showing up as "outer".
=> Make peerName a required field

as/in/karnataka/bangalore/mantri-pinnacle.k, as/sg/tanjong-pagar-centre.k, na/us/california/san-francisco/salesforce-tower.k
Sorry about not cleaning these out earlier :sweat_smile: Hope hyperboria is still doing well :)
=> Removing @belovachap's dead servers.

eu/de/bavaria/hype.jazzanet.com.k
=> deleted:    hype.jazzanet.com.k

eu/de/Frankfurt/h.rwfr.k, eu/fr/paris/h.rwfr.k
Due to my love of cjdns i have updated my node with new IP, i hope to keep cjdns alive with my public node for as long as i can.
Cheers to whoever needs to get integrated.
=> h.rwfr.k ip update

eu/nl/amsterdam/unloved.vultar.ams.k
there was updated file ``eu/nl/amsterdam/unloved.vultar.ams.k``, and ran ``./tests.py``
=> added IPv6 address to amsterdam/unloved.vultar.ams.k

eu/nl/amsterdam/mrowr.me.k
See: https://github.com/hyperboria/peers/issues/106#issuecomment-437296948
=> remove eu/nl/amsterdam/mrowr.me.k

sa/br/saopaulo/sp.yetanothernerd.xyz.k
Signed-off-by: Yan Minari <yangm97@gmail.com>
=> Add the first ever brazilian public cjdns peer

eu/nl/amsterdam/finlaydag33k.nl.k
Due to installing some new network equipment, my public IP has changed.  
As such, I have updated it to reflect these changes.
=> Updated IP

eu/fr/paris/h.totem.tfnux.org.k, eu/nl/amsterdam/h.mercury.tfnux.org.k
=> fix issue #128

na/us/california/orange-county/yk3music.k
=> Update and rename logic0x-markets-irvine.k to yk3music.k

eu/ch/zurich/0.h.pfactum.k
Signed-off-by: Oleksandr Natalenko <oleksandr@redhat.com>
=> eu/ch/zurich: add my peer

eu/ch/cjdns.theswissbay.ch
Quick update thanks to dynamic IPs !
=> Update cjdns.theswissbay.ch peer IP
